# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Appium iOS

on:
  push:
    branches: [ main ]

jobs:
  build:

#    runs-on: macos-10.15
    runs-on: macos-latest # the machine type
#    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 13.2.1
        run: sudo xcode-select -s /Applications/Xcode_13.2.1.app
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-node@v2
        with:
          node-version: '10.16.3'
      - run: |
          npm install -g appium@v1.20.2
          appium -v
          appium &>/dev/null &
          mvn clean test -Dcucumber.options="--tags @landIOS"